# Generated by Django 5.0.6 on 2024-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_message_writer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='upvote',
            field=models.IntegerField(default=0, verbose_name='upvote'),
        ),
    ]
