# Generated by Django 5.0.6 on 2024-09-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
