# Generated by Django 5.0.6 on 2024-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_message_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='downvote',
            field=models.IntegerField(default=0, verbose_name='downvote'),
        ),
        migrations.AlterField(
            model_name='message',
            name='upvote',
            field=models.IntegerField(default=0, verbose_name='upvote'),
        ),
    ]
