# Generated by Django 5.0.6 on 2024-09-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0005_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="Blog.photo"
            ),
        ),
    ]
