# Generated by Django 5.0.6 on 2024-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0006_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("undefined", "Undefined"),
                    ("feature", "Feature"),
                    ("fix", "Fix"),
                ],
                default="undefined",
                max_length=20,
            ),
        ),
    ]
