# Generated by Django 5.0.6 on 2024-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_message_downvote_alter_message_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='color'),
        ),
    ]
