# Generated by Django 5.0.6 on 2024-09-06 09:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0007_ticket_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sondage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "pub_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date publication"
                    ),
                ),
                ("current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SondageChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.TextField()),
                ("votes", models.IntegerField(default=0)),
                (
                    "sondage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Blog.sondage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChoiceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Blog.sondagechoice",
                    ),
                ),
            ],
        ),
    ]
