# Generated by Django 5.0.6 on 2024-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0008_sondage_sondagechoice_choiceuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sondagechoice",
            name="choice",
            field=models.TextField(blank=True),
        ),
    ]
