# Generated by Django 5.0.6 on 2024-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0008_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="session",
            field=models.IntegerField(default=0, verbose_name="session_id"),
        ),
    ]
