# Generated by Django 5.0.6 on 2024-08-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0009_message_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="session",
            new_name="session_id",
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Blog.message"
                    ),
                ),
            ],
        ),
    ]
