# Generated by Django 5.0.6 on 2024-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0010_recit_texte"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="yoda_counter",
            field=models.IntegerField(default=0, verbose_name="Yoda_counter"),
        ),
    ]
