# Generated by Django 5.0.6 on 2024-08-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0010_rename_session_message_session_id_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="message",
        ),
    ]
