# Generated by Django 5.0.6 on 2024-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0011_remove_session_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_name",
            field=models.TextField(default="", verbose_name="name"),
        ),
    ]
