# Generated by Django 5.0.6 on 2024-10-10 08:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0012_user_enjoy_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("sound", models.FileField(upload_to="Soundbox/")),
                (
                    "pub_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date publication"
                    ),
                ),
                ("tags", models.TextField(default="", verbose_name="tags")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Blog.sound"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
