# Generated by Django 5.0.6 on 2024-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0013_remove_message_session_id_message_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="session",
        ),
        migrations.AddField(
            model_name="message",
            name="session_id",
            field=models.IntegerField(default=0, verbose_name="session_id"),
        ),
    ]
