# Generated by Django 5.0.6 on 2024-08-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0014_remove_message_session_message_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Blog.session"
            ),
        ),
    ]
