# Generated by Django 5.0.6 on 2024-08-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0015_alter_usersession_session"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
