# Generated by Django 5.1 on 2024-10-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_box_item_user_coins_market_markethistory_skin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('color', models.CharField(default='#99E9E9', max_length=7, verbose_name='color')),
                ('probability', models.FloatField(default=0.69, verbose_name='probability')),
            ],
        ),
        migrations.AddField(
            model_name='skin',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.rarity'),
        ),
    ]
