# Generated by Django 5.1 on 2024-10-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_rarity_skin_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='type',
            field=models.CharField(choices=[('text_color', 'Text color'), ('border_color', 'Border color'), ('avatar_color', 'Avatar color'), ('name_color', 'Name color'), ('background_color', 'Background color'), ('background_image', 'Background image'), ('font', 'Font'), ('emoji', 'Emoji'), ('border_image', 'Border image'), ('other', 'Other')], default='other', max_length=64, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pattern',
            field=models.CharField(blank=True, max_length=64, verbose_name='pattern'),
        ),
        migrations.AlterField(
            model_name='market',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.item'),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.item'),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.item'),
        ),
    ]
