# Generated by Django 5.1 on 2024-10-21 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_skin_type_alter_item_pattern_alter_market_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='obtained_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='obtained_date'),
        ),
    ]
