# Generated by Django 5.0.6 on 2024-08-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0017_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="session_id",
            new_name="message_session_id",
        ),
    ]
