# Generated by Django 5.1 on 2024-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_userinventory_obtained_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventory',
            name='status',
        ),
        migrations.AddField(
            model_name='userinventory',
            name='equipped',
            field=models.BooleanField(default=False, verbose_name='equipped'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='favorite'),
        ),
    ]
