# Generated by Django 5.0.6 on 2024-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0018_rename_session_id_message_message_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_session_id",
            field=models.IntegerField(default=0, verbose_name="message_session_id"),
        ),
    ]
