# Generated by Django 5.0.6 on 2024-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0019_remove_userinventory_status_userinventory_equipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="skin",
            field=models.TextField(default="{}", verbose_name="message_skin"),
        ),
    ]
