# Generated by Django 5.0.6 on 2024-08-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0019_alter_message_message_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="message_session_id",
        ),
        migrations.RemoveField(
            model_name="session",
            name="id",
        ),
        migrations.AddField(
            model_name="message",
            name="message_session",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="Blog.session",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
