# Generated by Django 5.0.6 on 2024-08-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0020_remove_message_message_session_id_remove_session_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message_session",
            new_name="session_id",
        ),
    ]
