# Generated by Django 5.0.6 on 2024-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0021_rename_message_session_message_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="session_id",
            field=models.IntegerField(default=0, verbose_name="session_id"),
        ),
    ]
