# Generated by Django 5.1 on 2024-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_background_emojis_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='BorderImages/')),
            ],
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(upload_to='Boxes/'),
        ),
        migrations.AlterField(
            model_name='emojis',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='image',
            field=models.ImageField(upload_to='Skins/Box<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='type',
            field=models.CharField(choices=[('text_color', 'Text color'), ('border_color', 'Border color'), ('avatar_color', 'Avatar color'), ('name_color', 'Name color'), ('background_color', 'Background color'), ('background_image', 'Background image'), ('font', 'Font'), ('emoji', 'Emoji'), ('border_image', 'Border image'), ('name_rgb', 'Name RGB'), ('border_rgb', 'Border RGB'), ('other', 'Other')], default='other', max_length=64, verbose_name='type'),
        ),
    ]
