# Generated by Django 5.1 on 2024-10-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_alter_markethistory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='color',
        ),
    ]
