# Generated by Django 5.0.6 on 2024-11-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0024_remove_message_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tkt_counter",
            field=models.IntegerField(default=0, verbose_name="tkt_counter"),
        ),
    ]
