# Generated by Django 5.1.1 on 2024-11-08 09:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_user_tkt_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Date de vente'),
        ),
        migrations.CreateModel(
            name='OpeningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name="Date d'ouverture")),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.skin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
