# Generated by Django 5.0.6 on 2024-12-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0026_alter_markethistory_date_openinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="sondage",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Blog.session",
            ),
        ),
    ]
