# Generated by Django 5.1.1 on 2024-12-14 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0027_sondage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='llm_context',
            field=models.TextField(default='', verbose_name='llm_context'),
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprompt', models.TextField(default='', verbose_name='preprompt')),
                ('model_name', models.CharField(default='mixtral-8x7b-32768', max_length=100, verbose_name='model_name')),
                ('max_tokens', models.IntegerField(default=1024, verbose_name='max_tokens')),
                ('temperature', models.FloatField(default=1.0, verbose_name='temperature')),
                ('top_p', models.FloatField(default=0.95, verbose_name='top_p')),
                ('presence_penalty', models.FloatField(default=0.6, verbose_name='presence_penalty')),
                ('frequence_penalty', models.FloatField(default=0.6, verbose_name='frequence_penalty')),
                ('is_callable', models.BooleanField(default=False)),
                ('can_answer', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.bot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.session')),
            ],
        ),
    ]
