# Generated by Django 5.0.6 on 2025-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0029_enjoytimestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="karma",
            field=models.FloatField(default=0.0, verbose_name="karma"),
        ),
    ]
