# Generated by Django 5.1.5 on 2025-01-28 09:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0030_message_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='karma',
            field=models.FloatField(default=None, null=True, verbose_name='karma'),
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Flex', 'Flex')], max_length=100)),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 1, 28, 9, 49, 16, 946993, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
