# Generated by Django 5.1.5 on 2025-02-10 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0031_alter_message_karma_gamescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('Flex', 'Flex'), ('Tracker', 'Tracker'), ('Kingboard', 'Kingboard'), ('Bullet_Hell', 'Bullet_Hell')], max_length=100),
        ),
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('open', models.BooleanField(default=True)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PariIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('winning', models.BooleanField(blank=True, default=None, null=True)),
                ('pari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.pari')),
            ],
        ),
        migrations.CreateModel(
            name='UserForIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise', models.IntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pari_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.pariissue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
