# Generated by Django 5.1.5 on 2025-02-05 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0031_alter_message_karma_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('game', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('Flex', 'Flex'), ('Tracker', 'Tracker'), ('Kingboard', 'Kingboard'), ('Bullet_Hell', 'Bullet_Hell')], max_length=100),
        ),
    ]
