# Generated by Django 5.1.5 on 2025-02-06 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0031_alter_message_karma_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('players', models.IntegerField(default=1, verbose_name='players')),
                ('score', models.IntegerField(choices=[(-1, 'None'), (0, 'Lowest is best'), (1, 'Highest is best')], default=-1, verbose_name='score')),
            ],
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.game'),
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.game')),
            ],
        ),
    ]
