# Generated by Django 5.1.6 on 2025-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0032_game_alter_gamescore_date_alter_gamescore_game_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='gameType',
            field=models.CharField(choices=[('solo', 'solo'), ('1v1', '1v1'), ('2v2', '2v2'), ('3v1', '3v1'), ('FFA', 'FFA')], default='solo', max_length=4, verbose_name='gameType'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='token',
            field=models.CharField(default='', max_length=16),
        ),
    ]
