# Generated by Django 5.1.5 on 2025-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0034_pari_pariissue_userforissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='mise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
