# Generated by Django 5.1.5 on 2025-03-17 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0035_lobby_mise_lobby_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('n_min', models.IntegerField()),
                ('n_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot_type', models.CharField(choices=[('box', 'Box'), ('coins', 'Coins')], max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectifForQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_value', models.IntegerField(default=1)),
                ('current_value', models.IntegerField(default=0)),
                ('achieved', models.BooleanField(default=False)),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.objectifquest')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.quest')),
            ],
        ),
    ]
