# Generated by Django 5.1.6 on 2025-03-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0036_objectifquest_quest_objectifforquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
