# Generated by Django 5.1.5 on 2025-03-31 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0040_dwuserdinos_in_arena_dwuserteam_in_arena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDinoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('hp', 'Health'), ('atk', 'Attack'), ('defense', 'Defense'), ('spd', 'Speed'), ('crit', 'Critical Rate'), ('crit_dmg', 'Critical Damage')], max_length=8)),
                ('dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwuserdino')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.item')),
            ],
            options={
                'unique_together': {('dino', 'slot')},
            },
        ),
    ]
