# Generated by Django 5.1.5 on 2025-04-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0041_dwdinoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwdinoitem',
            name='slot',
            field=models.CharField(choices=[('hp', 'Health'), ('atk', 'Attack'), ('defense', 'Defense'), ('spd', 'Speed'), ('crit', 'Critical Rate'), ('crit_dmg', 'Critical Damage')], max_length=8),
        ),
    ]
