# Generated by Django 5.1.5 on 2025-04-03 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0043_dwuser_free_hatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwuser',
            name='arena_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DWArena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_str', models.CharField(default='', max_length=100)),
                ('team_str', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('win_streak', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.dwuserteam')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
