# Generated by Django 5.1.5 on 2025-04-09 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0044_dwuser_arena_energy_dwarena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwarena',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.dwuserteam'),
        ),
        migrations.AlterField(
            model_name='dwarena',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
