# Generated by Django 5.1.5 on 2025-04-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0045_alter_dwarena_team_alter_dwarena_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.journalentrytype')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryTypeForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_notification', models.BooleanField(default=True)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.journalentrytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
