# Generated by Django 5.1.5 on 2025-04-16 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0045_alter_dwarena_team_alter_dwarena_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWPvmAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmDino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=3000)),
                ('atk', models.IntegerField(default=100)),
                ('defense', models.IntegerField(default=100)),
                ('spd', models.FloatField(default=1.0)),
                ('crit', models.FloatField(default=0.05)),
                ('crit_dmg', models.FloatField(default=1.5)),
                ('attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.dwattack')),
                ('dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwdino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life', models.IntegerField(default=3)),
                ('level', models.IntegerField(default=1)),
                ('dino1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino1', to='Blog.dwpvmdino')),
                ('dino2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino2', to='Blog.dwpvmdino')),
                ('dino3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino3', to='Blog.dwpvmdino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmRunAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmability')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmrun')),
            ],
        ),
    ]
