# Generated by Django 5.1.5 on 2025-04-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0046_dwpvmability_dwpvmdino_dwpvmrun_dwpvmrunability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWPvmNextAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmability')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmrun')),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmNextFightDino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=3000)),
                ('atk', models.IntegerField(default=100)),
                ('defense', models.IntegerField(default=100)),
                ('spd', models.FloatField(default=1.0)),
                ('crit', models.FloatField(default=0.05)),
                ('crit_dmg', models.FloatField(default=1.5)),
                ('attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.dwattack')),
                ('dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwdino')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmrun')),
            ],
        ),
    ]
