# Generated by Django 5.1.5 on 2025-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0046_journalentrytype_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enjoytimestamp',
            name='note',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='note'),
        ),
    ]
