# Generated by Django 5.1.5 on 2025-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0047_dwpvmnextability_dwpvmnextfightdino'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwpvmrun',
            name='run_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-17 17:12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dwpvmrun',
            name='stat_points',
            field=models.IntegerField(default=0),
        ),
    ]
