# Generated by Django 5.1.5 on 2025-09-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0047_enjoytimestamp_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWPvmAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('to_dino', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='dwuser',
            name='free_pvm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwuser',
            name='pvm_runs_td',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dwfight',
            name='gamemode',
            field=models.CharField(choices=[('duel', 'Duel'), ('arena', 'Arena'), ('pvm', 'PvM')], default='duel', max_length=10),
        ),
        migrations.CreateModel(
            name='DWPvmDino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=3000)),
                ('atk', models.IntegerField(default=100)),
                ('defense', models.IntegerField(default=100)),
                ('spd', models.FloatField(default=1.0)),
                ('crit', models.FloatField(default=0.05)),
                ('crit_dmg', models.FloatField(default=1.5)),
                ('hp_lvl', models.IntegerField(default=1)),
                ('atk_lvl', models.IntegerField(default=1)),
                ('defense_lvl', models.IntegerField(default=1)),
                ('spd_lvl', models.IntegerField(default=1)),
                ('crit_lvl', models.IntegerField(default=1)),
                ('crit_dmg_lvl', models.IntegerField(default=1)),
                ('attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.dwattack')),
                ('dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwdino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmNewRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dino1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino1_new', to='Blog.dwpvmdino')),
                ('dino2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino2_new', to='Blog.dwpvmdino')),
                ('dino3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino3_new', to='Blog.dwpvmdino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life', models.IntegerField(default=3)),
                ('level', models.IntegerField(default=1)),
                ('stat_points', models.IntegerField(default=0)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('seen_abilities', models.TextField(default='[]')),
                ('dino1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino1', to='Blog.dwpvmdino')),
                ('dino2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino2', to='Blog.dwpvmdino')),
                ('dino3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino3', to='Blog.dwpvmdino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmNextFightDino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=3000)),
                ('atk', models.IntegerField(default=100)),
                ('defense', models.IntegerField(default=100)),
                ('spd', models.FloatField(default=1.0)),
                ('crit', models.FloatField(default=0.05)),
                ('crit_dmg', models.FloatField(default=1.5)),
                ('attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.dwattack')),
                ('dino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwdino')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmrun')),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmNextAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('is_discarded', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmability')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmrun')),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmRunAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmability')),
                ('dino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmdino')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmrun')),
            ],
        ),
        migrations.CreateModel(
            name='DWPvmLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('run_level', models.IntegerField()),
                ('team_dinos_stats', models.JSONField()),
                ('abilities_list', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmterrain')),
            ],
            options={
                'ordering': ['-run_level', '-date'],
            },
        ),
    ]
