# Generated by Django 5.1.5 on 2025-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0048_dwpvmrun_run_date_dwpvmrun_stat_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwpvmdino',
            name='atk_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dwpvmdino',
            name='crit_dmg_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dwpvmdino',
            name='crit_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dwpvmdino',
            name='defense_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dwpvmdino',
            name='hp_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dwpvmdino',
            name='spd_lvl',
            field=models.IntegerField(default=1),
        ),
    ]
