# Generated by Django 5.1.5 on 2025-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0048_dwpvmability_dwpvmterrain_dwuser_free_pvm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwpvmterrain',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
