# Generated by Django 5.1.5 on 2025-09-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0049_alter_dwpvmterrain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwpvmnewrun',
            name='terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.dwpvmterrain'),
        ),
        migrations.AddField(
            model_name='dwpvmrun',
            name='terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.dwpvmterrain'),
        ),
    ]
