# Generated by Django 5.1.5 on 2025-04-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0049_dwpvmdino_atk_lvl_dwpvmdino_crit_dmg_lvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwpvmability',
            name='to_dino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dwpvmnextability',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dwpvmnextability',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dwpvmrunability',
            name='dino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmdino'),
        ),
    ]
