# Generated by Django 5.1.5 on 2025-04-28 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0050_dwpvmability_to_dino_dwpvmnextability_is_discarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWPvmTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='dwpvmrun',
            name='seen_abilities',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='dwuser',
            name='free_pvm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwuser',
            name='pvm_runs_td',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DWPvmNewRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dino1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino1_new', to='Blog.dwpvmdino')),
                ('dino2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino2_new', to='Blog.dwpvmdino')),
                ('dino3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dino3_new', to='Blog.dwpvmdino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
