# Generated by Django 5.1.5 on 2025-10-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0050_dwpvmnewrun_terrain_dwpvmrun_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='first_unseen_message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.message'),
        ),
        migrations.AddField(
            model_name='sessionuser',
            name='unseen_messages_counter',
            field=models.IntegerField(default=0),
        ),
    ]
