# Generated by PyCharm on 2025-04-24 16:00

from django.db import migrations

def create_new_abilities(apps, schema_editor):
    """Create the new Vol de vie and Provocation abilities"""
    DWPvmAbility = apps.get_model('Blog', 'DWPvmAbility')
    
    # Create Vol de vie ability (individual dino ability)
    vol_de_vie, created = DWPvmAbility.objects.get_or_create(
        name="Vol de vie",
        defaults={
            'description': "Chaque attaque de ce dino le soigne de 15% des dégâts infligés.",
            'to_dino': True
        }
    )
    
    # Create Provocation ability (individual dino ability)
    provocation, created = DWPvmAbility.objects.get_or_create(
        name="Provocation",
        defaults={
            'description': "Ce dino a 2x plus de chances d'être la cible des attaques ennemies.",
            'to_dino': True
        }
    )

def remove_new_abilities(apps, schema_editor):
    """Remove the new abilities if migration is reversed"""
    DWPvmAbility = apps.get_model('Blog', 'DWPvmAbility')
    
    DWPvmAbility.objects.filter(name="Vol de vie").delete()
    DWPvmAbility.objects.filter(name="Provocation").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0051_dwpvmterrain_dwpvmrun_seen_abilities_dwuser_free_pvm_and_more'),
    ]

    operations = [
        migrations.RunPython(create_new_abilities, remove_new_abilities),
    ]