# Generated by Django 5.2.6 on 2025-09-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0051_dwpvmterrain_dwpvmrun_seen_abilities_dwuser_free_pvm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwfight',
            name='gamemode',
            field=models.CharField(choices=[('duel', 'Duel'), ('arena', 'Arena'), ('pvm', 'PvM')], default='duel', max_length=10),
        ),
        migrations.CreateModel(
            name='DWPvmLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('run_level', models.IntegerField()),
                ('team_dinos_stats', models.JSONField()),
                ('abilities_list', models.JSONField()),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.dwpvmterrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_level', '-date'],
            },
        ),
    ]
