# Generated by Django 5.1.5 on 2026-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0051_sessionuser_first_unseen_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homepage_preference',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2')], default='v1', max_length=50),
        ),
    ]
