# Generated by Django 6.0.4 on 2026-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0052_user_homepage_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nb_condamnations',
            field=models.IntegerField(default=0, verbose_name='nb_condamnations'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='type',
            field=models.CharField(choices=[('text_color', 'Text color'), ('border_color', 'Border color'), ('avatar_color', 'Avatar color'), ('name_color', 'Name color'), ('background_color', 'Background color'), ('background_image', 'Background image'), ('font', 'Font'), ('emoji', 'Emoji'), ('border_image', 'Border image'), ('name_rgb', 'Name RGB'), ('border_rgb', 'Border RGB'), ('other', 'Other'), ('collection', 'Collection')], default='other', max_length=64, verbose_name='type'),
        ),
    ]
