# Generated by Django 6.0.4 on 2026-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0053_user_nb_condamnations_alter_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
